# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LesionTool(object):
    def setupUi(self, LesionTool):
        LesionTool.setObjectName(_fromUtf8("LesionTool"))
        LesionTool.resize(872, 680)
        self.centralwidget = QtGui.QWidget(LesionTool)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.runButton = QtGui.QCommandLinkButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(350, 400, 168, 71))
        self.runButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runButton.setDescription(_fromUtf8(""))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(130, 80, 611, 320))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.main = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.main.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.main.setText(_fromUtf8(""))
        self.main.setObjectName(_fromUtf8("main"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.main)
        self.pushButton_main = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_main.sizePolicy().hasHeightForWidth())
        self.pushButton_main.setSizePolicy(sizePolicy)
        self.pushButton_main.setObjectName(_fromUtf8("pushButton_main"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton_main)
        self.label_23 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_23)
        self.acc = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.acc.setObjectName(_fromUtf8("acc"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.acc)
        self.pushButton_acc = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_acc.sizePolicy().hasHeightForWidth())
        self.pushButton_acc.setSizePolicy(sizePolicy)
        self.pushButton_acc.setObjectName(_fromUtf8("pushButton_acc"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButton_acc)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_26)
        self.name = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.name.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.name.setObjectName(_fromUtf8("name"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.name)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_24)
        self.workDir = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.workDir.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.workDir.setObjectName(_fromUtf8("workDir"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.FieldRole, self.workDir)
        self.pushButton_workDir = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_workDir.sizePolicy().hasHeightForWidth())
        self.pushButton_workDir.setSizePolicy(sizePolicy)
        self.pushButton_workDir.setObjectName(_fromUtf8("pushButton_workDir"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.FieldRole, self.pushButton_workDir)
        self.label_25 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_25)
        self.atlas = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.atlas.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.atlas.setObjectName(_fromUtf8("atlas"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.FieldRole, self.atlas)
        self.pushButton_atlas = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_atlas.sizePolicy().hasHeightForWidth())
        self.pushButton_atlas.setSizePolicy(sizePolicy)
        self.pushButton_atlas.setObjectName(_fromUtf8("pushButton_atlas"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.FieldRole, self.pushButton_atlas)
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(103, 490, 61, 24))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.inputDir = QtGui.QLineEdit(self.centralwidget)
        self.inputDir.setGeometry(QtCore.QRect(200, 490, 537, 24))
        self.inputDir.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.inputDir.setObjectName(_fromUtf8("inputDir"))
        self.pushButton_inputDir = QtGui.QPushButton(self.centralwidget)
        self.pushButton_inputDir.setGeometry(QtCore.QRect(200, 520, 85, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_inputDir.sizePolicy().hasHeightForWidth())
        self.pushButton_inputDir.setSizePolicy(sizePolicy)
        self.pushButton_inputDir.setObjectName(_fromUtf8("pushButton_inputDir"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(73, 560, 91, 24))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.subfile = QtGui.QLineEdit(self.centralwidget)
        self.subfile.setGeometry(QtCore.QRect(200, 560, 537, 24))
        self.subfile.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.subfile.setObjectName(_fromUtf8("subfile"))
        self.pushButton_subfile = QtGui.QPushButton(self.centralwidget)
        self.pushButton_subfile.setGeometry(QtCore.QRect(200, 590, 85, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_subfile.sizePolicy().hasHeightForWidth())
        self.pushButton_subfile.setSizePolicy(sizePolicy)
        self.pushButton_subfile.setObjectName(_fromUtf8("pushButton_subfile"))
        LesionTool.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(LesionTool)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        LesionTool.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(LesionTool)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionAbout = QtGui.QAction(LesionTool)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(LesionTool)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))

        self.retranslateUi(LesionTool)
        QtCore.QMetaObject.connectSlotsByName(LesionTool)

    def retranslateUi(self, LesionTool):
        LesionTool.setWindowTitle(_translate("LesionTool", "Lesion Tool", None))
        self.runButton.setToolTip(_translate("LesionTool", "launch the selected pipeline on the selected data with current parameters", None))
        self.runButton.setText(_translate("LesionTool", "Run Extraction", None))
        self.label_22.setText(_translate("LesionTool", "T1 - main", None))
        self.main.setToolTip(_translate("LesionTool", "XNAT server address", None))
        self.pushButton_main.setText(_translate("LesionTool", "select...", None))
        self.label_23.setText(_translate("LesionTool", "FLAIR - acc", None))
        self.acc.setToolTip(_translate("LesionTool", "login", None))
        self.pushButton_acc.setText(_translate("LesionTool", "select...", None))
        self.label_26.setText(_translate("LesionTool", "Name", None))
        self.name.setToolTip(_translate("LesionTool", "type in your password here...", None))
        self.label_24.setText(_translate("LesionTool", "Workdir", None))
        self.workDir.setToolTip(_translate("LesionTool", "type in your password here...", None))
        self.pushButton_workDir.setText(_translate("LesionTool", "select...", None))
        self.label_25.setText(_translate("LesionTool", "ATLAS", None))
        self.atlas.setToolTip(_translate("LesionTool", "type in your password here...", None))
        self.pushButton_atlas.setText(_translate("LesionTool", "select...", None))
        self.label_27.setText(_translate("LesionTool", "Input DIR", None))
        self.inputDir.setToolTip(_translate("LesionTool", "type in your password here...", None))
        self.pushButton_inputDir.setText(_translate("LesionTool", "select...", None))
        self.label_28.setText(_translate("LesionTool", "Subjects FILE", None))
        self.subfile.setToolTip(_translate("LesionTool", "type in your password here...", None))
        self.pushButton_subfile.setText(_translate("LesionTool", "select...", None))
        self.actionConfigure.setText(_translate("LesionTool", "manage configurations", None))
        self.actionAbout.setText(_translate("LesionTool", "About...", None))
        self.actionQuit.setText(_translate("LesionTool", "quit", None))

