# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nighres/lesion_tool/interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LesionTool(object):
    def setupUi(self, LesionTool):
        LesionTool.setObjectName(_fromUtf8("LesionTool"))
        LesionTool.resize(1114, 694)
        self.centralwidget = QtGui.QWidget(LesionTool)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 570, 211, 61))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_29 = QtGui.QLabel(self.formLayoutWidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.grid_selector = QtGui.QComboBox(self.formLayoutWidget)
        self.grid_selector.setObjectName(_fromUtf8("grid_selector"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.grid_selector)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 10, 591, 651))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.experimentsWidget = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.experimentsWidget.setObjectName(_fromUtf8("experimentsWidget"))
        self.SubjectWidget = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.SubjectWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SubjectWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.SubjectWidget.setAlternatingRowColors(True)
        self.SubjectWidget.setGridStyle(QtCore.Qt.NoPen)
        self.SubjectWidget.setColumnCount(2)
        self.SubjectWidget.setObjectName(_fromUtf8("SubjectWidget"))
        self.SubjectWidget.setRowCount(0)
        self.SubjectWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SubjectWidget.horizontalHeader().setSortIndicatorShown(True)
        self.SubjectWidget.horizontalHeader().setStretchLastSection(True)
        self.SubjectWidget.verticalHeader().setSortIndicatorShown(True)
        self.SubjectWidget.verticalHeader().setStretchLastSection(False)
        self.experimentsWidget.addWidget(self.SubjectWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectionToggle = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.selectionToggle.setObjectName(_fromUtf8("selectionToggle"))
        self.horizontalLayout.addWidget(self.selectionToggle)
        self.selectAll = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.selectAll.setObjectName(_fromUtf8("selectAll"))
        self.horizontalLayout.addWidget(self.selectAll)
        self.unselectAll = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.unselectAll.setObjectName(_fromUtf8("unselectAll"))
        self.horizontalLayout.addWidget(self.unselectAll)
        self.experimentsWidget.addLayout(self.horizontalLayout)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 540, 157, 14))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 409, 14))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 481, 71))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.inputDir = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.inputDir.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.inputDir.setText(_fromUtf8(""))
        self.inputDir.setObjectName(_fromUtf8("inputDir"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.inputDir)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_inputDir = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_inputDir.setObjectName(_fromUtf8("pushButton_inputDir"))
        self.horizontalLayout_5.addWidget(self.pushButton_inputDir)
        self.pushButton_loadInputDir = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_loadInputDir.setObjectName(_fromUtf8("pushButton_loadInputDir"))
        self.horizontalLayout_5.addWidget(self.pushButton_loadInputDir)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.formLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 481, 211))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.pushButton_workDir = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_workDir.sizePolicy().hasHeightForWidth())
        self.pushButton_workDir.setSizePolicy(sizePolicy)
        self.pushButton_workDir.setObjectName(_fromUtf8("pushButton_workDir"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButton_workDir)
        self.label_25 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_25)
        self.pushButton_atlas = QtGui.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_atlas.sizePolicy().hasHeightForWidth())
        self.pushButton_atlas.setSizePolicy(sizePolicy)
        self.pushButton_atlas.setObjectName(_fromUtf8("pushButton_atlas"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.pushButton_atlas)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(2, QtGui.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(5, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.name = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.name.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.name.setText(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.name)
        self.workDir = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.workDir.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.workDir.setText(_fromUtf8(""))
        self.workDir.setObjectName(_fromUtf8("workDir"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.workDir)
        self.atlas = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.atlas.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.atlas.setText(_fromUtf8(""))
        self.atlas.setObjectName(_fromUtf8("atlas"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.atlas)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 409, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 470, 461, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.runButton = QtGui.QCommandLinkButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(280, 570, 178, 36))
        self.runButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runButton.setDescription(_fromUtf8(""))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        LesionTool.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(LesionTool)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        LesionTool.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(LesionTool)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionAbout = QtGui.QAction(LesionTool)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(LesionTool)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))

        self.retranslateUi(LesionTool)
        QtCore.QMetaObject.connectSlotsByName(LesionTool)

    def retranslateUi(self, LesionTool):
        LesionTool.setWindowTitle(_translate("LesionTool", "WAIMEA Tool", None))
        self.label_29.setText(_translate("LesionTool", "Grid", None))
        self.SubjectWidget.setSortingEnabled(True)
        self.selectionToggle.setText(_translate("LesionTool", "Check selected", None))
        self.selectAll.setText(_translate("LesionTool", "Check all", None))
        self.unselectAll.setText(_translate("LesionTool", "Uncheck all", None))
        self.label_4.setText(_translate("LesionTool", "<html><head/><body><p><span style=\" font-weight:600;\">4. Run the extraction :</span></p></body></html>", None))
        self.label_3.setText(_translate("LesionTool", "<html><head/><body><p><span style=\" font-weight:600;\">2. Pick your preformated database and load it :</span></p></body></html>", None))
        self.inputDir.setToolTip(_translate("LesionTool", "XNAT server address", None))
        self.pushButton_inputDir.setText(_translate("LesionTool", "select...", None))
        self.pushButton_loadInputDir.setText(_translate("LesionTool", "Load", None))
        self.label_17.setText(_translate("LesionTool", "Input DIR", None))
        self.label_26.setText(_translate("LesionTool", "Name", None))
        self.label_24.setText(_translate("LesionTool", "Workdir", None))
        self.pushButton_workDir.setText(_translate("LesionTool", "select...", None))
        self.label_25.setText(_translate("LesionTool", "ATLAS", None))
        self.pushButton_atlas.setText(_translate("LesionTool", "select...", None))
        self.name.setToolTip(_translate("LesionTool", "XNAT server address", None))
        self.workDir.setToolTip(_translate("LesionTool", "XNAT server address", None))
        self.atlas.setToolTip(_translate("LesionTool", "XNAT server address", None))
        self.label_5.setText(_translate("LesionTool", "<html><head/><body><p><span style=\" font-weight:600;\">1. Fill this first form :</span></p></body></html>", None))
        self.label_6.setText(_translate("LesionTool", "<html><head/><body><p><span style=\" font-weight:600;\">3. Choose the subjects with the right-side box -----------------&gt;</span></p></body></html>", None))
        self.runButton.setToolTip(_translate("LesionTool", "launch the selected pipeline on the selected data with current parameters", None))
        self.runButton.setText(_translate("LesionTool", "Run Extraction", None))
        self.actionConfigure.setText(_translate("LesionTool", "manage configurations", None))
        self.actionAbout.setText(_translate("LesionTool", "About...", None))
        self.actionQuit.setText(_translate("LesionTool", "quit", None))

